version: "3.8"

services:
  db:
    image: postgres
    container_name: desafio_fullstack_users 
    ports: 
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata: 
    driver: local